In [4]:
train_path = "C:\\Users\\moham\\Desktop\\Phd_Google_drive_18thjuly2018\\Phd\\Datasets\\plant\\Plant Village.tar\\Plant Village\\train"

In [5]:
train_labels = os.listdir(train_path)

In [6]:
print(train_labels)

['Tomato___Bacterial_spot', 'Tomato___Early_blight', 'Tomato___healthy', 'Tomato___Late_blight', 'Tomato___Leaf_Mold', 'Tomato___Septoria_leaf_spot', 'Tomato___Spider_mites Two-spotted_spider_mite', 'Tomato___Target_Spot', 'Tomato___Tomato_mosaic_virus', 'Tomato___Tomato_Yellow_Leaf_Curl_Virus']


In [7]:
train_labels.sort()

In [4]:
print(PATH)

C:\Users\moham


In [7]:
train_path = "C:\\Users\\moham\\Desktop\\Phd_Google_drive_18thjuly2018\\Phd\\Datasets\\plant\\Plant Village.tar\\Plant Village\\train"

In [10]:
# organize imports
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler
import numpy as np
import mahotas
import cv2
import os
import h5py

# fixed-sizes for image
fixed_size = tuple((100, 100))
# path to training data
train_path = "C:\\Users\\moham\\Desktop\\Phd_Google_drive_18thjuly2018\\Phd\\Datasets\\plant\\Plant Village.tar\\Plant Village\\train"
print("train_path",train_path)
# no.of.trees for Random Forests
num_trees = 100

# bins for histogram
bins = 8

# train_test_split size
test_size = 0.10

# seed for reproducing same results
seed = 9

def fd_hu_moments(image):  
    image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    feature = cv2.HuMoments(cv2.moments(image)).flatten()
    return feature
def fd_haralick(image):
    # convert the image to grayscale
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    # compute the haralick texture feature vector
    haralick = mahotas.features.haralick(gray).mean(axis=0)
    # return the result
    return haralick
def fd_histogram(image, mask=None):
    # convert the image to HSV color-space
    image = cv2.cvtColor(image, cv2.COLOR_BGR2HSV)
    # compute the color histogram
    hist  = cv2.calcHist([image], [0, 1, 2], None, [bins, bins, bins], [0, 256, 0, 256, 0, 256])
    # normalize the histogram
    cv2.normalize(hist, hist)
    # return the histogram
    return hist.flatten()
# get the training labels
train_labels = os.listdir(train_path)

# sort the training labels
train_labels.sort()
print(train_labels)



train_path C:\Users\moham\Desktop\Phd_Google_drive_18thjuly2018\Phd\Datasets\plant\Plant Village.tar\Plant Village\train
['Tomato___Bacterial_spot', 'Tomato___Early_blight', 'Tomato___Late_blight', 'Tomato___Leaf_Mold', 'Tomato___Septoria_leaf_spot', 'Tomato___Spider_mites Two-spotted_spider_mite', 'Tomato___Target_Spot', 'Tomato___Tomato_Yellow_Leaf_Curl_Virus', 'Tomato___Tomato_mosaic_virus', 'Tomato___healthy']


In [12]:
# empty lists to hold feature vectors and labels
global_features = []
labels = []

i, j = 0, 0
k = 0

In [20]:

for training_name in train_labels:
    # join the training data path and each species training folder
    img_list = os.listdir(train_path + '/' + training_name)
    k=1
    current_label = training_name
    k = 1
    for img in img_list:
        image=train_path + '/' + training_name+'/' + img
        ip_img = cv2.imread(image)
        image = cv2.resize(ip_img, (100,100))
        
        ####################################
        # Global Feature extraction
        ####################################
        fv_hu_moments = fd_hu_moments(image)
        fv_haralick   = fd_haralick(image)
        fv_histogram  = fd_histogram(image)
###################################
        # Concatenate global features
        ###################################
        global_feature = np.hstack([fv_histogram, fv_haralick, fv_hu_moments])

        # update the list of labels and feature vectors
        labels.append(current_label)
        global_features.append(global_feature)

        i += 1
        k += 1
    print( "[STATUS] processed folder: {}".format(current_label))
    j += 1
    

[STATUS] processed folder: Tomato___Bacterial_spot
[STATUS] processed folder: Tomato___Early_blight
[STATUS] processed folder: Tomato___Late_blight
[STATUS] processed folder: Tomato___Leaf_Mold
[STATUS] processed folder: Tomato___Septoria_leaf_spot
[STATUS] processed folder: Tomato___Spider_mites Two-spotted_spider_mite
[STATUS] processed folder: Tomato___Target_Spot
[STATUS] processed folder: Tomato___Tomato_Yellow_Leaf_Curl_Virus
[STATUS] processed folder: Tomato___Tomato_mosaic_virus
[STATUS] processed folder: Tomato___healthy


In [21]:
print ("[STATUS] completed Global Feature Extraction...")
# get the overall feature vector size
print ("[STATUS] feature vector size {}".format(np.array(global_features).shape))

# get the overall training label size
print ("[STATUS] training Labels {}".format(np.array(labels).shape))

[STATUS] completed Global Feature Extraction...
[STATUS] feature vector size (18160, 532)
[STATUS] training Labels (18160,)


In [23]:
# encode the target labels
targetNames = np.unique(labels)
print(targetNames)

['Tomato___Bacterial_spot' 'Tomato___Early_blight' 'Tomato___Late_blight'
 'Tomato___Leaf_Mold' 'Tomato___Septoria_leaf_spot'
 'Tomato___Spider_mites Two-spotted_spider_mite' 'Tomato___Target_Spot'
 'Tomato___Tomato_Yellow_Leaf_Curl_Virus' 'Tomato___Tomato_mosaic_virus'
 'Tomato___healthy']


In [28]:

# encode the target labels
targetNames = np.unique(labels)
print(labels)
le = LabelEncoder()
print(le)
target = le.fit_transform(labels)
print(target)
print ("[STATUS] training labels encoded...")

# normalize the feature vector in the range (0-1)


['Tomato___Bacterial_spot', 'Tomato___Bacterial_spot', 'Tomato___Bacterial_spot', 'Tomato___Bacterial_spot', 'Tomato___Bacterial_spot', 'Tomato___Bacterial_spot', 'Tomato___Bacterial_spot', 'Tomato___Bacterial_spot', 'Tomato___Bacterial_spot', 'Tomato___Bacterial_spot', 'Tomato___Bacterial_spot', 'Tomato___Bacterial_spot', 'Tomato___Bacterial_spot', 'Tomato___Bacterial_spot', 'Tomato___Bacterial_spot', 'Tomato___Bacterial_spot', 'Tomato___Bacterial_spot', 'Tomato___Bacterial_spot', 'Tomato___Bacterial_spot', 'Tomato___Bacterial_spot', 'Tomato___Bacterial_spot', 'Tomato___Bacterial_spot', 'Tomato___Bacterial_spot', 'Tomato___Bacterial_spot', 'Tomato___Bacterial_spot', 'Tomato___Bacterial_spot', 'Tomato___Bacterial_spot', 'Tomato___Bacterial_spot', 'Tomato___Bacterial_spot', 'Tomato___Bacterial_spot', 'Tomato___Bacterial_spot', 'Tomato___Bacterial_spot', 'Tomato___Bacterial_spot', 'Tomato___Bacterial_spot', 'Tomato___Bacterial_spot', 'Tomato___Bacterial_spot', 'Tomato___Bacterial_spot', 

In [29]:


scaler = MinMaxScaler(feature_range=(0, 1))
rescaled_features = scaler.fit_transform(global_features)
print(rescaled_features)

[[0.         0.0038898  0.02752758 ... 0.17328771 0.19012512 0.29673719]
 [0.         0.01164614 0.12460548 ... 0.17328903 0.1901586  0.29674557]
 [0.00029982 0.00769342 0.0910758  ... 0.17328771 0.19014258 0.29674495]
 ...
 [0.00059991 0.0024053  0.00133506 ... 0.17328756 0.19014053 0.29674444]
 [0.00113804 0.00060838 0.0008442  ... 0.17328763 0.190141   0.29674431]
 [0.00133097 0.00142304 0.00049366 ... 0.17328756 0.19014003 0.29674444]]


In [30]:
print ("[STATUS] feature vector normalized...")

print ("[STATUS] target labels: {}".format(target))
print ("[STATUS] target labels shape: {}".format(target.shape))


[STATUS] feature vector normalized...
[STATUS] target labels: [0 0 0 ... 9 9 9]
[STATUS] target labels shape: (18160,)


In [31]:
# save the feature vector using HDF5
h5f_data = h5py.File('C:/PYTHON/dataSet/output/data.h5', 'w')
h5f_data.create_dataset('dataset_1', data=np.array(rescaled_features))

h5f_label = h5py.File('C:/PYTHON/dataSet/output/labels.h5', 'w')
h5f_label.create_dataset('dataset_1', data=np.array(target))

h5f_data.close()
h5f_label.close()

print ("[STATUS] end of training..")

[STATUS] end of training..


In [32]:
# import the necessary packages
import h5py
import numpy as np
import os
import glob
import cv2
from matplotlib import pyplot
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.model_selection import KFold, StratifiedKFold
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.externals import joblib


In [36]:
models = []
models.append(('SVM', SVC(random_state=9)))

# variables to hold the results and names
results = []
names = []
scoring = "accuracy"

# import the feature vector and trained labels
h5f_data = h5py.File('C:/PYTHON/dataSet/output/data.h5', 'r')
h5f_label = h5py.File('C:/PYTHON/dataSet/output/labels.h5', 'r')

global_features_string = h5f_data['dataset_1']
global_labels_string = h5f_label['dataset_1']

global_features = np.array(global_features_string)
global_labels = np.array(global_labels_string)

h5f_data.close()
h5f_label.close()

# verify the shape of the feature vector and labels
print ("[STATUS] features shape: {}".format(global_features.shape))
print ("[STATUS] labels shape: {}".format(global_labels.shape))

print ("[STATUS] training started...")

[STATUS] features shape: (18160, 532)
[STATUS] labels shape: (18160,)
[STATUS] training started...


In [38]:
(trainDataGlobal, testDataGlobal, trainLabelsGlobal, testLabelsGlobal) = train_test_split(np.array(global_features),
                                                                                          np.array(global_labels),
                                                                                          test_size=test_size,
                                                                                          random_state=seed)

print ("[STATUS] splitted train and test data...")
print ("Train data  : {}".format(trainDataGlobal.shape))
print ("Test data   : {}".format(testDataGlobal.shape))
print ("Train labels: {}".format(trainLabelsGlobal.shape))
print ("Test labels : {}".format(testLabelsGlobal.shape))

[STATUS] splitted train and test data...
Train data  : (16344, 532)
Test data   : (1816, 532)
Train labels: (16344,)
Test labels : (1816,)


In [ ]:
import warnings
print(models)

In [ ]:
for name, model in models:
    kfold = KFold(n_splits=10, random_state=7)
    cv_results = cross_val_score(model, trainDataGlobal, trainLabelsGlobal, cv=kfold, scoring=scoring)
    results.append(cv_results)
    names.append(name)
    msg = "%s: %f (%f)" % (name, cv_results.mean(), cv_results.std())
    print(msg)